# Generated by Django 4.2.10 on 2024-08-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_group_course_course_groups_alter_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course'),
            preserve_default=False,
        ),
    ]
