# Generated by Django 4.2.10 on 2024-08-19 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_remove_course_groups_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to=1, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
